#!/bin/sh
set -e

if command -v systemctl >/dev/null 2>&1; then
	systemctl daemon-reload || true
	if [ "$1" = "configure" ]; then
		systemctl enable networkmond.service >/dev/null 2>&1 || true
		systemctl restart networkmond.service >/dev/null 2>&1 || true
	fi
fi

exit 0
